
from django.urls import path
from . import views
# test me
urlpatterns = [
    path('transaction_summary/', views.TransactionSummary.as_view(),
         name='transaction_summary'),
    path('transaction_logger/', views.TransactionLogger.as_view(),
         name='transaction_logger'),
    path('pic_transaction_logger/', views.PicTransactionLogger.as_view(),
         name='pic_transaction_logger'), 
    path('pic_transaction_confirmation/', views.PicTransactionConfirmation.as_view(),
         name='pic_transaction_confirmation'), 
    path('pic_transaction_loggerv2/', views.PicTransactionLoggerV2.as_view(),
         name='pic_transaction_logger_v2'), 
    path('remote_config/', views.RemoteConfig.as_view(), name='remote_config'),
    path('pic_remote_config/', views.PicRemoteConfig.as_view(), name='pic_remote_config'),
    path('price_change/', views.PriceChange.as_view(), name='price_change'),
    path('raw_price_change/', views.RawPriceChangeData.as_view(),
         name='raw_price_change'),
    path('price_change/<int:pricechange_id>/',
         views.PriceChange.as_view(), name='price_change_authorize'),
    path('pumps/', views.Pumps.as_view(), name='pumps'),
    path('pumps/<int:pump_id>/', views.Pumps.as_view(), name='pumps_update'),
    path('pumps/toggle_activation/<int:pk>/',
         views.PumpsActivationDetails.as_view(), name='pumps_activation'),
    path('pumps/push_config/<int:pk>/',
         views.PushConfigToDevice.as_view(), name='push_config'),
    path('nozzle/', views.Nozzle.as_view(), name='nozzle'),
    path('nozzle/<int:nozzle_id>/', views.Nozzle.as_view(), name='nozzle_update'),
    path('nozzle_dashboard/', views.NozzleDashboard.as_view(),
         name='nozzle_dashboard'),
    path('nozzle_details/', views.NozzleDetails.as_view(),
         name='nozzle_ddetails'),
    path('pump_brand/', views.PumpBrand.as_view(), name="pump_brand"),
    path('pumps_site/', views.PumpsInSite.as_view(), name='pumps_site'),
    path('nozzle_trends/', views.NozzleTrends.as_view(), name='nozzle_trends'),
    path('site_price_change_request/', views.SitePriceChangeRequest.as_view(),
         name='site_price_change_request'),
    path('company_price_change_request/', views.CompanyPriceChangeRequest.as_view(),
         name='company_price_change_request'),
    path('price_execution_logger/', views.PriceExecutionLogger.as_view(),
         name='price_execution_logger'),
]
