# Generated by Django 2.2.15 on 2022-08-24 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nozzle',
            name='Nozzle_address_hex_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='nozzle',
            name='Decimal_setting_price_unit',
            field=models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
