# Generated by Django 2.2.15 on 2022-08-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_transactiondata_raw_nozzle_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nozzle',
            old_name='Nozzle_address_hex_code',
            new_name='Nozzle_addre',
        ),
    ]
