# Generated by Django 2.2.15 on 2022-08-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220825_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nozzle',
            old_name='Nozzle_addre',
            new_name='Nozzle_address_hex_code',
        ),
    ]
