# Generated by Django 2.2.15 on 2022-08-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_smartsolardata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartsolardata',
            name='mac_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
