# Generated by Django 2.2.15 on 2022-09-01 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20220831_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartsolardata',
            old_name='log_time',
            new_name='energy_meter_log_time',
        ),
        migrations.AddField(
            model_name='smartsolardata',
            name='device_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='smartsolardata',
            name='inverter_log_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
