# Generated by Django 2.2.15 on 2022-09-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20220901_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartsolardata',
            name='device_type',
        ),
    ]
