# Generated by Django 2.2.15 on 2022-09-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_smartsolardata_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartsolardata',
            name='device_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
