# Generated by Django 2.2.15 on 2022-09-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20220905_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartsolardata',
            name='energy_time_log',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartsolardata',
            name='inv_time_log',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
