from django.urls import path
from . import views

# test cicd
urlpatterns = [
    path('genhours_logger/', views.GeneratorHoursLogger.as_view(),
         name='genhours_logger'),
    path('fm_logger/', views.FlowmeterLogger.as_view(), name='flowmeter_logger'),
    path('pm_logger/', views.PowermeterLogger.as_view(), name='powermeter_logger'),
    path('equipment_dashboard/', views.EquipmentDashboardView.as_view(),
         name='equipment_dashboard'),
    path('equipment_map/', views.EquipmentMap.as_view(), name='equipment_map'),
    path('total_hours_report/', views.TotalHoursReport.as_view(),
         name='total_hours_report'),
    path('litres_consumed_report/', views.EquipmentConsumptionReport.as_view(),
         name='litres_consumed_report'),
    path('daily_24_hours_range_consumption_report/', views.Daily24HrsRangeConsumptionReport.as_view(),
         name='daily_24hrs_litres_consumed_report'),
    path('hours_daily_trend/', views.HoursDailyTrend.as_view(),
         name='hours_daily_trend'),
    path('litres_consumed_daily_trend/', views.EquipmentConsumptionDailyTrend.as_view(),
         name='litres_consumed_daily_trend'),
    path('consumption_rates_daily_trend/', views.EquipmentDailyConsumptionRatesTrend.as_view(),
         name='consumption_rates_daily_trend'),
    path('total_hours_range/', views.HoursDistribution.as_view(),
         name='hours_in_range'),
    path('litres_consumed_range/', views.LitresConsumedDistribution.as_view(),
         name='litres_consumed_in_range'),
    path('flowmeter_test_transactions/', views.EquipmentFlowmeterTestTransactionReport.as_view(),
         name="flowmeter_test_transactions"),
    path('equipment_transaction_logs/', views.EquipmentFlowmeterTransactionLogs.as_view(),
         name='equipment_transaction_logs'),
    path('equipment_transaction_trends/', views.EquipmentFlowmeterTransactionTrends.as_view(),
         name='equipment_transaction_trends'),
    path('new_transaction_comment/', views.TransactionComment.as_view(),
         name='new_transaction_comment'),
    path('transaction_comment/<int:pk>', views.TransactionCommentDetail.as_view(),
         name='transaction_comment_update'),
    path('powermeter_transaction_logs/', views.PowerMeterTransactionLogs.as_view(),
         name='powermeter_transaction_log'),
    path('powermeter_transaction/', views.PowerMeterTransaction.as_view(),
         name='powermeter_transaction'),
    path('powermeter_update/', views.PowerMeterUpdate.as_view(),
         name='powermeter_update'),
    path('equipment_list/', views.EquipmentList.as_view(),
         name='all_equipment_site_list'),
    path('equipment_obj/', views.EquipmentObj.as_view(), name='equipment_obj'),
    path('powermeters/by_company/', views.ViewPowerMetersByCompany.as_view(),
         name='powermeters_by_company'),
    path('powermeters/by_companies/', views.ViewPowerMetersByMultipleCompany.as_view(),
         name='powermeters_by_many_company'),
    path('all_powermeters/', views.ViewAllPowermeters.as_view(),
         name='all_powermeters'),
    path('activate_deactivate_powermeter/<int:powermeter_id>/<str:action>/',
         views.ActivateDeactivatePowermeter.as_view(), name='activate_deactivate_powermeters'),
    path('powermeter_lastlog/', views.PowermeterLastLog.as_view(),
         name='powermeter_lastlog'),
    path('powermeter_logs/', views.PowermeterLogs.as_view(), name='powermeter_logs'),
    path('daily_power_trend/', views.DailyPowerTrend.as_view(),
         name='daily_power_trend'),
    path('consumption_load/', views.ConsumptionLoad.as_view(),
         name='consumption_load'),
    path('powerlog_cycle/', views.PowerLogPerCycle.as_view(), name='powerlog_cycle')
]
